#cloud-config

# Create the docker group
groups:
  - docker

# Install Docker
runcmd:
  - curl -fsSL https://get.docker.com | sh
  - systemctl start docker
  - systemctl enable docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]